style: gitlab
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://gitlab.iktns.ru/vdrepa/clear-addon.git
options:
  tag_filter_pattern: '^v'
  sort: "date"

  commits:
    sort_by: Scope
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - style
        - docs
        - chore

  commit_groups:
    group_by: Type
    sort_by: Title # Date needed
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      style: Code Style
      docs: Documentation Edits
      chore: Chores

  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  
  issues:
    prefix:
      - #
  
  refs:
    actions:
      - Closes
      - Fixes

  notes:
    keywords:
      - BREAKING CHANGE